sudo: required

services:
  - docker 

before_install:
  - docker build -t sakiori/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true sakiori/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-410898602605Info"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  


